### PR TITLE
worker: centralize ticks

### PR DESCRIPTION
**Pull request by ttaylorr**
@connor4312 please review carefully

### CODE REVIEW

**Comment by connor4312** [comment]
This has been carefully reviewed and my careful analysis leads me to the careful conclusion that it is acceptable.

**Comment by ttaylorr** [comment]
Carefully merging... :dancer:

**Comment by connor4312** [comment]
inb4'd

**Comment by ttaylorr** [comment]
Carefully deleted.

**Comment by connor4312** [comment]
inb'8'ed

**Pull request merged**
